name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: dummy-app/Dockerfile
          push: true
          tags: ${{ secrets.ECR_REPOSITORY }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}